### ISSUE TITLE
MSF library

### ISSUE THREAD

**Issue by aido** [udoklein/dcf77#3]
Hi Udo,

I am considering using you most excellent DCF77 library as a basis for an MSF library.

However, there are a few differences between the DCF77 and MSF protocols.

### DCF77
* The last second of the minute is always a 1000 ms low period. This is also known as 'the sync mark'.
* The other 59 (or, exceptionally, 60 or 58) seconds of the minute always begin with at least 100 ms high period, followed by a single data bit of 100 ms, and end with at least 800 ms low period.
	* Data bit is transmitted from 100 to 200 ms after the second
* If each second is considered as ten 100 ms pieces, the minute marker is transmitted as 0000000000, while all other seconds are transmitted as 1D00000000.

### MSF
* The first second of the minute begins with a 500 ms low period, to serve as a minute marker.
* The other 59 (or, exceptionally, 60 or 58) seconds of the minute always begin with at least 100 ms low period, followed by two data bits of 100 ms each, and end with at least 700 ms high period.
	* Data bit A is transmitted from 100 to 200 ms after the second
	*  Data bit B is transmitted from 200 to 300 ms after the second
* If each second is considered as ten 100 ms pieces of negative polarity bit signalling, the minute marker is transmitted as 1111100000, while all other seconds are transmitted as 1AB0000000.

https://en.wikipedia.org/wiki/Time_from_NPL#Protocol

Do you think these differences make your DCF77 library impractical to use as the basis of an MSF library?

Thanks in advance for your response.

**Comment by udoklein** [comment]
Hi Aido,

this is the same question that Paul asked here: http://blog.blinkenlight.net/experiments/dcf77/dcf77-library/. I answered it on November 6, 2014 at 19:48. Since you are asking here you have step 0 already in place ;)

Maybe you can team up with Paul. If you have any more specific questions just ask. In doubt ask at my block because there is more traffic there and your chances to find someone who is willing to team up might be higher. For any specific questions, just ask me. I will answer whenever my time permits.

Cheers, Udo
