### ISSUE TITLE
Local_Clock not initialized

### ISSUE THREAD

**Issue by nameoftherose** [udoklein/dcf77#30]
I noticed that the Local_Clock is not initialized, its setup method (dcf77.h line 1323) is never being executed.
Is there a reason for that?

**Comment by udoklein** [comment]
The local clock is automatically initialized. However from a consistency point of view I think the clock controller should call the setup anyway. The setup method was introduced because everything else also has a setup method. This can be useful during testing.

Fixing the issue might make the code slightly larger without adding any benefits. I will test a little bit on the size impact.

**Comment by nameoftherose** [comment]
I have done the modification you describe, but now I think it is better to leave it as is. The sketch should call it if necessary.
